### ISSUE TITLE
.gitignoreを追加する

### ISSUE THREAD

**Issue by tenax66** [nakashima723/P2Pslyr#8]
.gitignoreファイルをリポジトリに追加して、`__pycache__`などのgitにcommitする必要のないファイルを自動的に無視できるようにする。

参考: [.gitignoreについて](https://qiita.com/y_minowa/items/e3d8513dc31c1b378e0d)

**Comment by nakashima723** [comment]
Python用のを隠しファイルとして追加してみました。これで大丈夫でしょうか？

**Comment by tenax66** [comment]
4004fea20b8e79e25cc1b7fde58d06350f94436a　
こちらの内容で機能しました！ ありがとうございます。
